services:
  php:
    build:
      context: ./.docker/php
    container_name: ${APP_NAME}-php
    user: "${UID}:${GID}"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mssql
    env_file:
      - ./.env
    networks:
      - yii2net

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./app:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - yii2net

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ${APP_NAME}-mssql
    environment:
      SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "${MSSQL_DB_PORT}:1433"
    volumes:
      - yii2_mssql_data:/var/opt/mssql
    networks:
      - yii2net

networks:
  yii2net:
    driver: bridge
    name: "${APP_NAME}-network"

volumes:
  yii2_mssql_data: